### ISSUE TITLE
Sorting issues

### ISSUE THREAD

**Issue by mariusc** [Lascorbe/CocoaConferences#159] opened 2018-12-20 07:19 UTC
The upcoming Cocoa-only conferences are sorted in the wrong order. I think they should be sorted with the upcoming one first, and the furthers away in the future down.

![image](https://user-images.githubusercontent.com/844175/50269698-c832de00-0437-11e9-99cd-fccea4b0e37f.png)

Almost the same issue is valid for sorting the mobile conferences, where the order is again reversed, except for MobileEra (the last one), which seems to break the order completely

![image](https://user-images.githubusercontent.com/844175/50269705-d123af80-0437-11e9-8f22-a614dc3b84e6.png)

The past Cocoa-only conferences seem to be in the right order, as far as I can see.

But the past mobile development conferences also have a small problem with the order, starting with 3 conferences from 2018, then all the other ones in ascending order.

![image](https://user-images.githubusercontent.com/844175/50269855-573ff600-0438-11e9-9556-ee2c05123532.png)

**Comment by Lascorbe** [comment] 2018-12-20 10:36
It's looking good for me, maybe it has something to do because it's comparing against your local date? cc @davedelong 

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/1515520/50279915-67ad9c00-044b-11e9-94ed-f95f440e3223.png">

**Comment by mariusc** [comment] 2018-12-20 10:52
Weird... Not sure exactly how I can help debug this. I'm using Google Chrome Version 71.0.3578.98, timezone is EEST (Bucharest). And here are the Language and Region settings:

![image](https://user-images.githubusercontent.com/844175/50280657-c4ae4f80-0455-11e9-8cbd-642bccf85b5a.png)

Just tried in Safari, and everything seems ok there. Firefox also seems to show the correct order. So far it seems it's only happening on Google Chrome for me.

**Comment by lazerwalker** [comment] 2018-12-20 12:56
If this is a client-side issue, one (relatively high-effort) way to get around this might be to rewrite the new JS so that the rendering logic happens at compile-time (which might require a rewrite into Ruby / Jekyll, not sure?). Since this project uses Jekyll to serve up the pages, GitHub automatically recompiles the site whenever new commits are pushed, which would give us hooks to regenerate static HTML. I'm curious if GH Pages' templating infrastructure gives us a way to do this using the existing JS templating logic.

Besides removing the potential for a client's date settings to muck with sorting, this would also e.g. let the site work for users who have JS disabled.

**Comment by davedelong** [comment] 2018-12-20 18:30
Also: I just confirmed that only Google Chrome is getting the sorting wrong. How bizarre.

**Comment by davedelong** [comment] 2018-12-20 18:47
Aha, after some investigation, I think I've figured it out. The `.sort()` method takes a function that is supposed to return `-1`, `0`, or `1` (analogous to `ComparisonResult.orderedSame`, `.orderedAscending`, and `.orderedDescending`). Right now it's only returning `true` or `false`.

I'll work up a PR to fix this.

**Comment by davedelong** [comment] 2018-12-20 19:41
Fixed by #162

**Closed by davedelong** 2018-12-20 19:41 UTC

**Comment by Lascorbe** [comment] 2018-12-21 11:58
Thanks @davedelong @lazerwalker & @mariusc for taking the time to look into this 🍻
